services:
    #
    # Security
    #

    acilia.oauth_authorization.enabled:
        class: Acilia\Bundle\OauthAuthorizationBundle\Service\EnabledService
        arguments: ['@request_stack', '%acilia_oauth.enabled%', '%acilia_oauth.excludes%']

    acilia.oauth_authorization.token_authenticator:
        class: Acilia\Bundle\OauthAuthorizationBundle\Security\TokenAuthenticator
        arguments: ['%acilia_oauth.access_url%', '@acilia.oauth_authorization.enabled', '%acilia_oauth.client_id%', '%acilia_oauth.api_tokens%']

    # User Provider
    acilia.oauth_authorization.oauth_access_user_provider:
        class: Acilia\Bundle\OauthAuthorizationBundle\Security\UserProvider
        arguments: ['%acilia_oauth.access_url%', '@acilia.oauth_authorization.enabled',  '%acilia_oauth.oauth_secret%', '%acilia_oauth.client_id%']

    acilia.oauth_authorization.logout_success_handler:
        class: Acilia\Bundle\OauthAuthorizationBundle\Security\LogoutSuccessHandler
        arguments: ['%acilia_oauth.access_url%']
